Alpha
RimacTechnology/semantic-release-s3 pull request #2
Opened 2022-11-22 12:31 UTC by erikkiralj1

This PR is the initial implementation of a semantic-release plugin to push files and folders to AWS S3 bucket. Bucket name and directory path are passed into the config, with the ability to remove the root directory of the defined path.

2022-11-22 13:27 UTC, vuki656 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +                    'I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-ecr/issues) and there
Old link

2022-11-22 13:27 UTC, vuki656 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          label: '`semantic-release-ecr` Version You Are Using'
Old name

2022-11-22 13:27 UTC, vuki656 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          description: 'Paste the config you are using with `semantic-release-ecr` from semantic release config file'
Old name

2022-11-22 13:27 UTC, vuki656 commented on .github/ISSUE_TEMPLATE/feature_requrest.yml
> +                    I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-ecr/issues) and there are
Old link

2022-11-22 13:27 UTC, vuki656 commented on .github/ISSUE_TEMPLATE/feature_requrest.yml
> +description: Request a feature request for `semantic-release-ecr`
Old name

2022-11-22 13:27 UTC, vuki656 commented on .prettierignore
> +CHANGELOG.md # If your project contains it
No need for that comment

2022-11-22 13:27 UTC, vuki656 commented on package.json
> +        "lint:spell": "cspell --no-progress --no-summary '**'",
Rename `spell` to `cspell` to be consistent

2022-11-22 13:27 UTC, vuki656 commented on package.json
> +        "node": ">=16.14",
Can you use node 18?

2022-11-22 13:27 UTC, vuki656 commented on src/aws.ts
> +                // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
Is the error null if the response is valid?

2022-11-22 13:27 UTC, vuki656 commented on src/aws.ts
> +                    if (error) {
Is the error null if the response is valid?

2022-11-22 13:27 UTC, vuki656 commented on src/aws.ts
> +                // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
Is the error null if the response is valid?

2022-11-22 15:34 UTC, mario-jerkovic requested changes

2022-11-23 08:27 UTC, vuki656 approved these changes

2022-11-23 08:28 UTC, mario-jerkovic approved these changes

2022-11-23 08:34 UTC, merged

2022-11-27 19:55 UTC, rimac-technology commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@rimac-technology/semantic-release-s3/v/1.0.0)
- [GitHub release](https://github.com/RimacTechnology/semantic-release-s3/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: